### ISSUE TITLE
exclusive layer visibility

### ISSUE THREAD

**Issue by carsen-stringer** [chanzuckerberg/napari-plugin-alfa-cohort#28]
I was wondering if it's possible (and useful) to have exclusive layer visibility. I often flash between the cell probability layer and the flow layer and the image layer in the cellpose GUI, which would require auto-turning off at least one layer in napari.

**Comment by sofroniewn** [comment]
Hi @carsen-stringer this is something we don't support yet, but was recently requested here https://github.com/napari/napari/issues/2166. It's always great to get two requests for the same feature, so we'll get on implementing something soon! Feel free to continue this discussion on that issue in the main napari repo if you have additional thoughts on it

**Comment by carsen-stringer** [comment]
oh awesome, thanks!
